### ISSUE TITLE
[Feature]: Extend password length slider range to 4-34

### ISSUE THREAD

**Issue by maisondasilva** [XFox111/PasswordGeneratorExtension#286]
### Proposed solution

Add 4 - 34 character password generation!

### Justification

Currently it is from 6 to 32 but there is a case where I need 4 or 34 characters!

### Alternatives

Suggest options!

### Additional context

I accept suggestion!

### Are you willing to submit a PR for this issue?

no

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by XFox111** [comment]
Hi. It is in there. You can set your password length to 4 or 34 in extension's settings.

<img width="344" alt="image" src="https://github.com/XFox111/PasswordGeneratorExtension/assets/28831743/f4fe6d66-554f-4ada-8f89-1a48ed478ae8">

It's the quick adjustment slider that has some additional logic:
- Default min/max values of the slider are 6-32
- If your default length is out of the range, the slider's range will adjust (e.g. if your default length is 4, then the slider's range will be 4-32 and vice versa)

I've made it this way, so the slider doesn't have a great range, otherwise it would be hard to manipulate.

Though, I could make some adjustments to the UX. I am not happy about current state of the quick adjustments bar, so I'll think what I can do about it.

**Comment by maisondasilva** [comment]
@XFox111 Thanks
Yes, I had already done that, but when I need a password with 4 numbers I need to change it down and when I need one with 34 numbers I need to change it again, can you leave the default between 4 and 34 in the quick setting?

Thanks
Maison

**Comment by XFox111** [comment]
Hi @maisondasilva. I've reworked quick adjustments section for the next version. Can you test this and give me your thoughts? Note, that this is a WIP, so it has some bugs.

[TabsAside-286-WIP.zip](https://github.com/XFox111/PasswordGeneratorExtension/files/14202280/TabsAside-286-WIP.zip)

**Comment by maisondasilva** [comment]
It was very good! With this new version need to translate anything new?
You could leave it by default between 4 and 34, this would be very useful for the customers me install it!

![image](https://github.com/XFox111/PasswordGeneratorExtension/assets/11423362/8300f3ad-3f88-4f00-8b9d-ab2a479e7eca)

Thanks

**Comment by maisondasilva** [comment]
![image](https://github.com/XFox111/PasswordGeneratorExtension/assets/11423362/0c4ad2ce-f951-49cd-a9a3-3d08d4a473cd)

Between the lines it would be nice to have a space for design ends!

**Comment by XFox111** [comment]
Great! I'll prepare the PR tomorrow.

> With this new version need to translate anything new?

Not exactly. Copilot surprisingly does a great job. However, I'll put you into reviewers to make sure that the wording is good.

> You could leave it by default between 4 and 34, this would be very useful for the customers me install it!
I think the password pattern instead of 8 could also be 10

I'll lower it to 4 characters, but I'm keeping the upper bar and default length as is. These are optimal for the most of users.

> Between the lines it would be nice to have a space for design ends

This is a number range, and the rules tell that there should be no spaces (besides, in my opinion it looks worse with them). Though I'll change the dash character, since apparently it should be en dash (–) instead of em dash (—).
